### ISSUE TITLE
Skill increases cause stats to reset (health, magicka, fatigue)

### ISSUE THREAD

**Issue by IllyaMoskvin** [hristoast/ncgd-tes3mp#2]
During a skill increase, it seems that the player's health, magicka, and fatigue get reset back to whatever they were during their "last recorded" state. I haven't yet looked into what scenarios cause your stats to be recorded, but I've been able to replicate this via cell transitions:

1. Go to an exterior cell (e.g. Balmora)
2. Reduce your health, magicka, and fatigue through normal means.
3. While your stats are reduced, enter an interior cell with a trainer (e.g. Balmora Mage's Guild).
4. Restore your stats without leaving that cell. (I've tested resting and casting restore spells.)
5. Obtain training from an NPC.
6. Note how your stats are reduced back down to the values they had when you entered the cell.

Tentatively, I've also been able to replicate this by damaging myself, exiting the game, reloading, healing, and training. My stats get reduced down to whatever they were when I reloaded.

This bug seems to happen even when the skill increase does not trigger an attribute increase.

Running the `/ncgd health` command in chat also works instead of training.

In practice, I've noticed this bug causing three gameplay issues. First, I tend to restore fatigue before bartering. If bartering causes mercantile to increase, my fatigue will be reset back to whatever it was when I entered the store, requiring me to exit out of the conversation to restore it. Secondly, this bug can cause unfair character death if the player heals after entering a cell. Thirdly, it can also be abused as a sort of auto-heal to train armor skills.

From testing TES3MP without NCGD, I think the default behavior is to treat the time spent training as waiting. In practice, fatigue will be restored, but health and magicka will stay the same.

I suspect that this is related to the `player:LoadStatsDynamic()` call on [main.lua#L761](https://github.com/hristoast/ncgd-tes3mp/blob/14a08e9839dd001e3b420cd34bc1bd38f15a1d89/main.lua#L761).

**Comment by hristoast** [comment]
Fixed by #5
