### ISSUE TITLE
"The Lady" birthsign is ignored when calculating health

### ISSUE THREAD

**Issue by IllyaMoskvin** [hristoast/ncgd-tes3mp#3]
Currently, NCGD does not take into account the 25-point Endurance boost from [The Lady](https://en.uesp.net/wiki/Morrowind:Birthsigns#The_Lady).

From the UESP article on [Endurance](https://en.uesp.net/wiki/Morrowind:Endurance):

> Only your base endurance and the Fortify Endurance from abilities **(In the original game, only The Lady Sign)** are used to calculate your additional health on level up. For example, if you have 50 base Endurance and +20 from a Fortify Endurance effect other than from The Lady Sign, your total Endurance will be 70; however, you will get only an additional 5 health when you level up. Note that increases to endurance do not retroactively increase hit points, so it is advisable to maximize endurance as soon as possible.

Looking at "Abilities" under "Spellmaking" in the Construction Set, I cannot find anything else that gives an Endurance boost. I do see that some vampirism abilities grant a Strength or Willpower boost, and per the logic of NCGD, it might make sense to take that into account for health.

However, per the [FAQ for v0.7.0](https://steamcommunity.com/groups/mwmulti/discussions/1/353916184342480541/):

>Spell effects and diseases are not saved to or loaded from the server. This means all of them will disappear when you log out and rejoin.

...so since vampirism isn't going to be saved to server, there's no real need to support it for now.

Originally, I was going to ask if it might make sense to account for fortify and drain attribute effects when calculating health, even if these effects came from temporary sources (e.g. spells or potions).

For example, here's how I did it in [TES3MP-MBSP](https://github.com/IllyaMoskvin/tes3mp-mbsp/blob/52fbccda0a508f33df14c255f185446a2a6ee3dc/main.lua#L299-L301):

```lua
local willpowerAttributeId = tes3mp.GetAttributeId('Willpower')

local currentWillpower = tes3mp.GetAttributeBase(pid, willpowerAttributeId) +
    tes3mp.GetAttributeModifier(pid, willpowerAttributeId) -
    tes3mp.GetAttributeDamage(pid, willpowerAttributeId)
```

Considering all of the possible scenarios that might cause the player to gain such effects, plus the limitation quoted above, it seems like the cleanest way to honor fortify and drain is to check the player's attributes every second and recalculate health if there is a change.

That seems doable, but I'm not sure if the "timer on repeat" aspect would cause performance issues. It feels like a bad idea, but I think we'd have to test it to know for sure.

In either case, TES3MP does track birthsigns, and checking if `player.data.character.birthsign` is `lady's favor` feels like low-hanging fruit. Given that Morrowind honors the birthsign when calculating health, NCGD ignoring it feels like a bug.

**Comment by hristoast** [comment]
Fixed by https://github.com/hristoast/tes3mp-ncgd/pull/4
