### ISSUE TITLE
Incorrect script reference on line #549

### ISSUE THREAD

**Issue by Tsarenir** [hristoast/ncgd-tes3mp#7]
Sorry if title is confusing but, I've just set up a server with fresh files all downloaded and installed just this morning, and after spending most of the day figuring out why my server was crashing, I finally narrowed it down to NCGD-TES3MP, specifically line #549
Here is the error I was receiving:
[2020-10-24 22:31:30] [ERR]: .\server\scripts\custom/ncgd-tes3mp/main.lua:549: bad argument #1 to 'lower' (string expected, got nil)
[2020-10-24 22:31:30] [ERR]: [Script]: Server crash from script error!

Here is line #549 in the main.lua

  temp2 = temp * **ncgdTES3MP.config.growthRates**[string.lower(**ncgdTES3MP.config.growthRate**)]

the script referenced should be 

  temp2 = temp * **ncgdTES3MP.defaultConfig.growthRates**[string.lower(**ncgdTES3MP.defaultConfig.growthRate**)]

After changing this call I have managed to get my server running for me to play on, with no crash so far.

**Comment by hristoast** [comment]
That's not a typo; The table `ncgdTES3MP.config` is populated with values from your config file (`__config_ncgdTES3MP.json`). If that's got `nil` values, then the content is bad.

Revert the change you mention above, rename your `__config_ncgdTES3MP.json` file, and then see if you still have the same problem.

**Comment by Tsarenir** [comment]
All right, it seems to have resolved after renaming the file mentioned and generating a new config, not sure what happened with the first one but thank you, I never would've tried that. Sorry for the false report.

**Comment by hristoast** [comment]
No worries at all! Glad that ended up being it, I'm pretty sure something like a missing comma in the config could cause this.

In the future, an extension to DataManager that tells the user when there's a config or data issue would be nice (meaning the contents are malformed in some way, or anything else).

In any case I'll close this out.
